installCRDs: true

serviceAccount:
  annotations:
    "eks.amazonaws.com/role-arn": ${role_arn}

securityContext:
  fsGroup: 1001

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node.kubernetes.io/lifecycle
          operator: In
          values: 
            - ondemand

cainjector:
  enabled: true
  replicaCount: 1

  extraArgs:
    - --leader-elect=false
